<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View otevaluationperiod');

if(isset($_GET['period']))
{
    $period = urldecode($_GET['period']);
    require 'form_data_otevaluationperiod.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_back']);

    if($_POST['btn_back'])
    {
        log_action('Pressed cancel button');
        require 'components/query_string_standard.php';
        redirect("listview_otevaluationperiod.php?$query_string");
    }
}
require 'subclasses/otevaluationperiod_html.php';
$html = new otevaluationperiod_html;
$html->draw_header('Detail View: Otevaluationperiod', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->detail_view = TRUE;
$html->draw_controls('view');

$html->draw_footer();