<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Set User Passports');

$showUsers=FALSE;

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);

    $module = $_POST['module'];

    $check = array();
    if(isset($_POST['check']))
    {
        $check  = $_POST['check'];
    }

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect('SetUserPassports.php');
    }

    if($_POST['btn_delete'])
    {
        if(isset($check) && is_array($check))
        {
            $data_con = new data_abstraction;
            $data_con->set_query_type('DELETE');

            $obj_role = new data_abstraction();
            $obj_role->set_query_type('UPDATE');
            $obj_role->set_table('user');
            $obj_role->set_update("role_id='0'");

            foreach($check as $user)
            {
                $data_con->set_table('user_passport');
                $data_con->set_where("username='" . quote_smart($user) . "' AND link_id='" . quote_smart($module) . "'");
                $data_con->make_query();

                $obj_role->set_where("username='" . quote_smart($user) . "'");
                $obj_role->make_query();
            }
            $data_con->close_db();
            $obj_role->close_db();
        }
        else
        {
            $message = "Please select at least one user.";
        }
    }

    $data_con = new data_abstraction;
    $data_con->set_fields('username');
    $data_con->set_table('user_passport');
    $data_con->set_where("link_id='" . quote_smart($module) . "'");
    $data_con->set_order('username');
    if($result = $data_con->make_query()->result)
    {
        $arrUser = array();
        $showUsers=TRUE;
        $numUsers = $data_con->num_rows;
        for($a=0; $a<$numUsers; $a++)
        {
            $data = $result->fetch_assoc();
            extract($data);

            $arrUser[] = $username;
        }
    }
}

$html_writer = new html;
$html_writer->draw_header('Set User Passports', $message, $message_type);
?>

<div class="container">
<fieldset class="container_invisible">
<fieldset class="top"> View Users Per Module, and Revoke Permissions</fieldset>
<fieldset class="middle">
<table class="input_form" width="800">
<tr><td><a href="set_user_passports.php">[Custom Permissions]</a> :: <b>[View and Remove Permissions Per Module]</b> :: <a href="set_user_passports3.php">[Role-Based Access Control Interface]</a><hr></td>
</table>
<table width="75%" cellpadding="2" cellspacing="2" align="center" class="input_form">
<?php
$query = "SELECT link_id, descriptive_title FROM `user_links` ORDER BY descriptive_title";
$value = 'link_id';
$items = array('descriptive_title');
$html_writer->draw_select_field_from_query($query, $value, $items, 'Module','module',FALSE,TRUE,'','onChange="show_loading_div(); this.form.submit();"');
?>
</table>
<?php
if($showUsers)
{
    echo '<table width="600" cellpadding="2" cellspacing="2" align="center" class="listView">';
    echo '<tr class="listRowHead"><td align="center" width="50">[X]</td> <td> Username </td></tr>';
    for($a=0; $a<$numUsers; $a++)
    {
        if($a%2==0) $class='listRowOdd';
        else $class='listRowEven';
        echo '<tr class="' . $class . '">';
        echo '<td align="center">';
        echo '<label style="display: block" for="' . $arrUser[$a] . '">';
        echo '<input type="checkbox" id="' . $arrUser[$a] . '" name="check[]" value="' . $arrUser[$a] . '">';
        echo '</label>';
        echo '</td>';
        echo '<td>';
        echo '<label style="display: block" for="' . $arrUser[$a] . '">
                &nbsp;&nbsp;' . $arrUser[$a] . '</label></td>';
        echo '</td>';
        echo '</tr>';
    }
    $html_writer->draw_button('SPECIAL', 'button1', 'btn_delete', 'REMOVE ACCESS', TRUE, '2');
    echo '</table>';
}
?>
</fieldset>
</fieldset>
</div>
<?php $html_writer->draw_footer();
