<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Delete system settings');

if(isset($_GET['setting']))
{
    $setting = urldecode($_GET['setting']);
    require 'form_data_system_settings.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_system_settings.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require 'subclasses/system_settings.php';
        $dbh_system_settings = new system_settings;

        $object_name = 'dbh_system_settings';
        require 'components/create_form_data.php';

        $dbh_system_settings->delete($arr_form_data);


        redirect("listview_system_settings.php?$query_string");
    }
}
require 'subclasses/system_settings_html.php';
$html = new system_settings_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('setting');

$html->detail_view = TRUE;

$html->draw_controls('delete');

$html->draw_footer();
