<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Edit system skins');

if(isset($_GET['skin_id']))
{
    $skin_id = urldecode($_GET['skin_id']);
    require 'form_data_system_skins.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/system_skins.php';
    $dbh_system_skins = new system_skins;

    $object_name = 'dbh_system_skins';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_system_skins.php?$query_string");
    }

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_system_skins->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_system_skins->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_system_skins->edit($arr_form_data);
            redirect("listview_system_skins.php?$query_string");
        }
    }
}
require 'subclasses/system_skins_html.php';
$html = new system_skins_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('skin_id');


$html->draw_controls('edit');

$html->draw_footer();
