<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('View user');

$db_subclass   = 'user';
$html_subclass = 'user_html';
$page_title    = 'ListView: %%';
$add_link      = 'Add user';
$add_page      = 'add_user.php';
$edit_link     = 'Edit user';
$edit_page     = 'edit_user.php';
$delete_link   = 'Delete user';
$delete_page   = 'delete_user.php';
$view_link     = 'View user';
$view_page     = 'detailview_user.php';
$csv_page      = ''; //disabled on purpose to avoid accidentally dumping contents of user table (confidential data, hashed passwords)
$report_page   = 'reporter_user.php';
$arr_pkey_name = array('username');
$results_per_page = 50;

require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';
