<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('View system skins');

$page_title       = 'ListView: %%';
$db_subclass      = 'system_skins';
$html_subclass    = 'system_skins_html';
$arr_pkey_name = array('skin_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add system skins';
$edit_link        = 'Edit system skins';
$delete_link      = 'Delete system skins';
$view_link        = 'View system skins';

//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_system_skins.php';
$edit_page        = 'edit_system_skins.php';
$delete_page      = 'delete_system_skins.php';
$view_page        = 'detailview_system_skins.php';
$csv_page         = 'csv_system_skins.php';
$report_page      = 'reporter_system_skins.php';

//Extra entries under operations column (name of include file, not html code)
$operations_extra = '';

//Formatting and alignment options for data columns
$arr_formatting   = array();
$arr_alignment    = array();

require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';
