<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Set User Passports');

$SHOW_MODULES=FALSE;
$fromSuccess='';

if(isset($_GET['Username']) && $_GET['Username'] != "")
{
    $Username = $_GET['Username'];
    $fromSuccess="YES";
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    init_var($_POST['find']);
    init_var($_POST['passportButton']);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect(HOME_PAGE);
    }

    $Username      = $_POST['Username'];
    $passportGroup = $_POST['passportGroup'];

    $link=array();
    if(isset($_POST['link']))
    {
        $link = $_POST['link'];
    }

    if(isset($_POST['numLinks']))
    {
        $numLinks = $_POST['numLinks'];
    }

    if(($_POST['find']) || ($_POST['passportButton']) || ($fromSuccess=="YES"))
    {
        $data_con = new data_abstraction;
        $data_con->set_fields('a.person_id, b.role_id, b.role, c.first_name, c.middle_name, c.last_name');
        $data_con->set_table('user a LEFT JOIN person c ON a.person_id=c.person_id LEFT JOIN user_role b ON a.role_id=b.role_id');
        $data_con->set_where("a.username='" . quote_smart($Username) . "' AND a.person_id = c.person_id");
        $result = $data_con->make_query()->result;
        $numrows = $data_con->num_rows;
        $data_con->close_db();

        if($numrows==1)
        {
            $data = $result->fetch_assoc();
            extract($data);
            $Name = $first_name . ' ' . $middle_name . ' ' . $last_name;
            $Role_ID = $role_id;
            $Role = $role;
            if($Role == '') $Role = "No Role Assigned";

            $SHOW_MODULES=TRUE;
        }
        elseif($numrows==0)
        {
            $message = 'No match found for username you entered.';
            $message_type = 'error';
            $_POST['passportButton'] = FALSE;
            $_POST['find'] = FALSE;
            $Name='';
            $Role='';
            $Role_ID='';
        }
    }

    if($_POST['btn_submit'])
    {
        $Name = $_POST['Name'];

        $completeList='';
        if($passportGroup!="All Groups")
        {
            $data_con = new data_abstraction;
            $data_con->set_fields('link_id');
            $data_con->set_table('user_links');
            $data_con->set_where("passport_group_id='" . quote_smart($passportGroup) . "'");
            $result = $data_con->make_query()->result;
            $numrows = $data_con->num_rows;
            $data_con->close_db();
            if($numrows>0)
            {
                for($a=0;$a<$numrows;$a++)
                {
                    $info=$result->fetch_row();
                    if($a != ($numrows - 1)) $completeList = $completeList . "'$info[0]',";
                    else $completeList = $completeList . "'$info[0]'";
                }

                $data_con = new data_abstraction;
                $data_con->set_query_type('DELETE');
                $data_con->set_table('user_passport');
                $data_con->set_where("username='" . quote_smart($Username) . "' AND link_id IN ($completeList)");
                $data_con->make_query();
                $data_con->close_db();
            }
        }
        else
        {
            $data_con = new data_abstraction;
            $data_con->set_query_type('DELETE');
            $data_con->set_table('user_passport');
            $data_con->set_where("username='" . quote_smart($Username) . "'");
            $data_con->make_query();
            $data_con->close_db();
        }

        if(count($link)>0)
        {
            $data_con = new data_abstraction;
            $data_con->set_query_type('INSERT');
            $data_con->set_table('user_passport');
            $data_con->set_fields('username, link_id');
            $arr_values = array();
            for($a=0;$a<$numLinks;$a++)
            {
                if(isset($link[$a]))
                {
                    $arr_values[] = "'" . quote_smart($Username) . "', '$link[$a]'";
                }
            }
            $data_con->set_values($arr_values);
            $data_con->make_query();
            $data_con->close_db();
        }

        //Finally: since a custom permission operation was done, set role to 0 (no role assigned)
        $dbh = new data_abstraction();
        $dbh->set_query_type('UPDATE');
        $dbh->set_table('user');
        $dbh->set_update("role_id='0'");
        $dbh->set_where("username='" . quote_smart($Username) . "'");
        $dbh->make_query();
        $dbh->close_db();
        $Role = 'No Role Assigned';

        $message = 'Passport settings succesfully updated';
        $message_type = 'system';
        $SHOW_MODULES=TRUE;
    }
}
$html_writer = new html;
$html_writer->draw_header('Set User Passports', $message, $message_type);
?>
<div class="container">
<fieldset class="container_invisible">
<fieldset class="top"> Modify the System Privileges of Users</fieldset>
<fieldset class="middle">
<table class="input_form" width="800">
<tr><td><b>[Custom Permissions]</b> :: <a href="set_user_passports2.php">[View and Remove Permissions Per Module]</a> :: <a href="set_user_passports3.php">[Role-Based Access Control Interface]</a><hr></td>
</table>
<table class="input_form">
<?php
init_var($Username);
init_var($Name);
init_var($Role);
init_var($passportGroup);
?>
<tr><td class="label"> Username: </td><td colspan=3><input type=text name="Username" value="<?php echo $Username; ?>"> <input type=submit name=find value="FIND" class=button1></td></tr>
<tr><td class="label"> Full Name: </td><td><input type=text name="Name" size=30 value="<?php echo $Name; ?>" readonly></td>
    <td class="label"> Current Role: </td><td><input type=text name="Role" value="<?php echo $Role; ?>" readonly></td></tr>
<tr><td class="label"> Passport Group: </td><td colspan=3>
    <SELECT NAME=passportGroup>
    <?php
    echo '<option selected>All Groups</option>';
    $data_con = new data_abstraction;
    $data_con->connect_db();
    $data_con->set_fields('passport_group_id, passport_group AS Passport_Group_Name');
    $data_con->set_table('user_passport_groups');
    $data_con->set_order('passport_group');
    if($result = $data_con->make_query()->result)
    {
        $a=0;
        while($data = $result->fetch_assoc())
        {
            extract($data);
            $selected = '';
            if($passport_group_id == $passportGroup) $selected = 'selected';
            echo "<option value='$passport_group_id' $selected> $Passport_Group_Name </option>";
        }
        $result->close();
    }
    else die($data_con->error);
    $data_con->close_db();
    ?>
    </SELECT> <input type=submit name="passportButton" value="GO" class=button1>
    </td>
</tr>
</TABLE>

<table class="input_form" width="800">
<tr><td><br><hr></td></tr>
</table>

<?php
if($SHOW_MODULES)
{
    if($passportGroup != 'All Groups')
    {
        $data_con = new data_abstraction;
        $data_con->connect_db();
        $data_con->set_fields('passport_group AS `Group_Title`');
        $data_con->set_table('user_passport_groups');
        $data_con->set_where("passport_group_id = '" . quote_smart($passportGroup) . "'");
        $result = $data_con->make_query()->result;
        $data_con->close_db();

        $info = $result->fetch_assoc();
        extract($info);
    }
    else $Group_Title = "All Groups";
?>
    <br><br>
    <table width="800" class="listView" align="center">
    <tr class="listRowHead"><td colspan=2> <?php echo "$Group_Title passport for $Name";?></td></tr>
    <tr><td colspan=2>
        <input type=button name=CHECK value="CHECK ALL" class="button1" onClick="checkAll();">
        <input type=button name=UNCHECK value="UNCHECK ALL" class="button1" onClick="uncheckAll();">
    </td></tr>
    <?php
    $data_con = new data_abstraction;
    $data_con->set_fields('a.link_id, a.descriptive_title AS `Module_Name`');
    $data_con->set_table('user_links a, user_passport_groups b');

    if($passportGroup!="All Groups")
        $data_con->set_where("a.passport_group_id = b.passport_group_id AND b.passport_group_id='$passportGroup'");
    elseif($passportGroup=="All Groups")
        $data_con->set_where("a.passport_group_id = b.passport_group_id AND b.passport_group_id!=''");

    $data_con->set_order('a.descriptive_title');
    $result = $data_con->make_query()->result;
    $numrows= $data_con->num_rows;
    $data_con->close_db();
    echo '<input type="hidden" name="numLinks" value="' . $numrows . '">';

    for ($a=0;$a<$numrows;$a+=2)
    {
        if($a%4==0) $class='listRowOddNoHighlight';
        else $class='listRowEvenNoHighlight';

        $info=$result->fetch_assoc();
        extract($info);

        $data_con = new data_abstraction;
        $data_con->set_fields('username');
        $data_con->set_table('user_passport');
        $data_con->set_where("username='" . quote_smart($Username) . "' AND link_id='$link_id'");
        $data_con->make_query();

        $checked = '';
        if($data_con->num_rows==1) $checked = 'checked';

        echo "<TR class=$class><td class=\"listCell\"><label style=\"display: block;\" for='checkfield[$a]'><input type=checkbox ID='checkfield[$a]' name=\"link[]\" value='$link_id' $checked> $Module_Name</label></td>";

        $data_con->close_db();

        if(($a+1) < $numrows)
        {
            $info=$result->fetch_assoc();
            extract($info);

            $data_con = new data_abstraction;
            $data_con->set_fields('username');
            $data_con->set_table('user_passport');
            $data_con->set_where("username='" . quote_smart($Username) . "' AND link_id='$link_id'");
            $data_con->make_query();

            if($data_con->num_rows==0)     echo "<td class='listCell'><label style=\"display: block;\" for=\"checkfield[" . ($a+1) . "]\"><input type=checkbox ID='checkfield[" . ($a+1) . "]' name=\"link[]\" value='$link_id'> $Module_Name</label></td></tr>";
            elseif($data_con->num_rows==1) echo "<td class='listCell'><label style=\"display: block;\" for=\"checkfield[" . ($a+1) . "]\"><input type=checkbox ID='checkfield[" . ($a+1) . "]' name=\"link[]\" value='$link_id' checked> $Module_Name</label></td></tr>";

            $data_con->close_db();
        }
        else echo "<td class='listCell'> &nbsp; </td></tr>";
    }
    if($numrows > 0)
    {
        echo '<tr><td colspan=2 align=center>
                <br />
                <input type="submit" name="btn_submit" value="SUBMIT" class="submit">
                <input type="submit" name="btn_cancel" value="BACK" class="cancel">
                <br /><br />';
    }
    else
    {
        echo "<tr><td colspan=2> No modules found for this passport group. Please choose a different passport group.";
    }
    ?>
    </td></tr>
    </table>
<?php
}
else
{
    echo "<br><input type=submit name=btn_cancel value='BACK' class=button1>";
}
echo '</fieldset>';
echo '</fieldset>';
echo '</div>';
$html_writer->draw_footer();
?>
<script language="JavaScript" type="text/JavaScript">
function checkAll()
{

    var arrCheckBoxes = document.getElementsByName('link[]');
    for (var i = 0; i < arrCheckBoxes.length; i++)
    {
        arrCheckBoxes[i].checked = true;
    }
}
function uncheckAll()
{
    var arrCheckBoxes = document.getElementsByName('link[]');
    for (var i = 0; i < arrCheckBoxes.length; i++)
    {
        arrCheckBoxes[i].checked = false;
    }
}
</script>
<?php
