<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete availability');

if(isset($_GET['availability_id']))
{
    $availability_id = urldecode($_GET['availability_id']);
    require_once 'form_data_availability.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_availability.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/availability.php';
        $dbh_availability = new availability;

        $object_name = 'dbh_availability';
        require 'components/create_form_data.php';


        $dbh_availability->delete($arr_form_data);

        redirect("listview_availability.php?$query_string");
    }
}
require 'subclasses/availability_html.php';
$html = new availability_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('availability_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();