<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add facultyload');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/facultyload.php';
    $dbh_facultyload = new facultyload;

    $object_name = 'dbh_facultyload';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_facultyload.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_facultyload->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_facultyload->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_facultyload->add($arr_form_data);
            $load_id = $dbh_facultyload->auto_id;
            require_once 'subclasses/refsubjectofferinghdr.php';
            $dbh_facultyload = new refsubjectofferinghdr;
            for($a=0; $a<$refsubjectofferinghdr_count;$a++)
            {
                
                $param = array(
                               'term_id'=>$cf_refsubjectofferinghdr_term_id[$a],
                               'subject_id'=>$cf_refsubjectofferinghdr_subject_id[$a],
                               'section'=>$cf_refsubjectofferinghdr_section[$a],
                               'subject_code'=>$cf_refsubjectofferinghdr_subject_code[$a],
                               'load_id'=>$load_id,
                               'emp_id'=>$cf_refsubjectofferinghdr_emp_id[$a]
                              );
                $dbh_facultyload->add($param);
            }


            redirect("listview_facultyload.php?$query_string");
        }
    }
}
require 'subclasses/facultyload_html.php';
$html = new facultyload_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();