<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete facultyload');

if(isset($_GET['load_id']))
{
    $load_id = urldecode($_GET['load_id']);
    require_once 'form_data_facultyload.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_facultyload.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/facultyload.php';
        $dbh_facultyload = new facultyload;

        $object_name = 'dbh_facultyload';
        require 'components/create_form_data.php';

        require_once 'subclasses/refsubjectofferinghdr.php';
        $dbh_refsubjectofferinghdr = new refsubjectofferinghdr;
        $dbh_refsubjectofferinghdr->delete_many($arr_form_data);


        $dbh_facultyload->delete($arr_form_data);

        redirect("listview_facultyload.php?$query_string");
    }
}
require 'subclasses/facultyload_html.php';
$html = new facultyload_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('load_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();