<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit otevaluationperiod');

if(isset($_GET['period']))
{
    $period = urldecode($_GET['period']);
    require 'form_data_otevaluationperiod.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/otevaluationperiod.php';
    $dbh_otevaluationperiod = new otevaluationperiod;

    $object_name = 'dbh_otevaluationperiod';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_otevaluationperiod.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_otevaluationperiod->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_otevaluationperiod->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_otevaluationperiod->edit($arr_form_data);


            redirect("listview_otevaluationperiod.php?$query_string");
        }
    }
}
require 'subclasses/otevaluationperiod_html.php';
$html = new otevaluationperiod_html;
$html->draw_header('Edit Otevaluationperiod', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('period');

$html->draw_controls('edit');

$html->draw_footer();