<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Reset Password');

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect(HOME_PAGE);
    }

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        require 'subclasses/user.php';
        $dbh_user = new user;

        $dbh_user->fields['password']['required'] = TRUE;
        $dbh_user->fields['skin_id']['required'] = FALSE;
        $dbh_user->fields['person_id']['required'] = FALSE;

        $arr_form_data = array('username'=>$_POST['username'],
                               'password'=>$_POST['password']);

        $message .= $dbh_user->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if(strlen($password) > MAX_PASSWORD_LENGTH)
        {
            $message = 'Password must not be more than ' . MAX_PASSWORD_LENGTH . ' chars.';
            $password = '';
        }

        //check if user exists
        if($dbh_user->check_user($username)->user_exists)
        {
            //Good
        }
        else
        {
            $message = 'Specified username does not exist.';
        }

        if($message=="")
        {
            require 'password_crypto.php';
            $hashed_password = cobalt_password_hash('NEW',$password, $username, $new_salt, $new_iteration, $new_method);

            $data_con = new data_abstraction;
            $data_con->set_query_type('UPDATE');
            $data_con->set_table('user');
            $data_con->set_update("`password`='$hashed_password', `salt`='$new_salt', `iteration`='$new_iteration', `method`='$new_method'");
            $data_con->set_where("username='" . quote_smart($username) . "'");
            $data_con->make_query();
            $message = 'The password has been successfully reset.';
            $message_type='SYSTEM';
            $password   = '';
        }
    }
}
require 'subclasses/user_html.php';
$html = new user_html;
$html->draw_header('Reset Password', $message, $message_type);
$html->fields['password']['control_type'] = 'password';
$html->fields['password']['label'] = 'Temporary Password';
$html->exception = array('person_id','role_id','skin_id');
$html->draw_controls('add','Password Reset Form');
$html->draw_footer();
