<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete refsubjectoteclassification');

if(isset($_GET['period']) && isset($_GET['subject_id']))
{
    $period = urldecode($_GET['period']);
    $subject_id = urldecode($_GET['subject_id']);
    require_once 'form_data_refsubjectoteclassification.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_refsubjectoteclassification.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/refsubjectoteclassification.php';
        $dbh_refsubjectoteclassification = new refsubjectoteclassification;

        $object_name = 'dbh_refsubjectoteclassification';
        require 'components/create_form_data.php';

        $dbh_refsubjectoteclassification->delete($arr_form_data);


        redirect("listview_refsubjectoteclassification.php?$query_string");
    }
}
require 'subclasses/refsubjectoteclassification_html.php';
$html = new refsubjectoteclassification_html;
$html->draw_header('Delete Refsubjectoteclassification', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('period');
$html->draw_hidden('subject_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();