<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete otevaluationresults');

if(isset($_GET['period']) && isset($_GET['target_id']) && isset($_GET['class_id']))
{
    $period = urldecode($_GET['period']);
    $target_id = urldecode($_GET['target_id']);
    $class_id = urldecode($_GET['class_id']);
    require_once 'form_data_otevaluationresults.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_otevaluationresults.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/otevaluationresults.php';
        $dbh_otevaluationresults = new otevaluationresults;

        $object_name = 'dbh_otevaluationresults';
        require 'components/create_form_data.php';

        $dbh_otevaluationresults->delete($arr_form_data);


        redirect("listview_otevaluationresults.php?$query_string");
    }
}
require 'subclasses/otevaluationresults_html.php';
$html = new otevaluationresults_html;
$html->draw_header('Delete Otevaluationresults', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('period');
$html->draw_hidden('target_id');
$html->draw_hidden('class_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();