<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Delete cobalt sst');

if(isset($_GET['auto_id']))
{
    $auto_id = urldecode($_GET['auto_id']);
    require_once 'form_data_cobalt_sst.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_cobalt_sst.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/cobalt_sst.php';
        $dbh_cobalt_sst = new cobalt_sst;

        $object_name = 'dbh_cobalt_sst';
        require 'components/create_form_data.php';

        $dbh_cobalt_sst->delete($arr_form_data);


        redirect("listview_cobalt_sst.php?$query_string");
    }
}
require 'subclasses/cobalt_sst_html.php';
$html = new cobalt_sst_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('auto_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();
