<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete specialization');

if(isset($_GET['specialization_id']))
{
    $specialization_id = urldecode($_GET['specialization_id']);
    require_once 'form_data_specialization.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_specialization.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/specialization.php';
        $dbh_specialization = new specialization;

        $object_name = 'dbh_specialization';
        require 'components/create_form_data.php';

        require_once 'subclasses/subject.php';
        $dbh_subject = new subject;
        $dbh_subject->delete_many($arr_form_data);


        $dbh_specialization->delete($arr_form_data);

        redirect("listview_specialization.php?$query_string");
    }
}
require 'subclasses/specialization_html.php';
$html = new specialization_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('specialization_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();