<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete otevaluationratings');

if(isset($_GET['period']) && isset($_GET['stud_id']) && isset($_GET['item_id']) && isset($_GET['target_id']) && isset($_GET['subject_code']) && isset($_GET['section']))
{
    $period = urldecode($_GET['period']);
    $stud_id = urldecode($_GET['stud_id']);
    $item_id = urldecode($_GET['item_id']);
    $target_id = urldecode($_GET['target_id']);
    $subject_code = urldecode($_GET['subject_code']);
    $section = urldecode($_GET['section']);
    require_once 'form_data_otevaluationratings.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_otevaluationratings.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/otevaluationratings.php';
        $dbh_otevaluationratings = new otevaluationratings;

        $object_name = 'dbh_otevaluationratings';
        require 'components/create_form_data.php';

        $dbh_otevaluationratings->delete($arr_form_data);


        redirect("listview_otevaluationratings.php?$query_string");
    }
}
require 'subclasses/otevaluationratings_html.php';
$html = new otevaluationratings_html;
$html->draw_header('Delete Otevaluationratings', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('period');
$html->draw_hidden('stud_id');
$html->draw_hidden('item_id');
$html->draw_hidden('target_id');
$html->draw_hidden('subject_code');
$html->draw_hidden('section');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();