<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Delete user');

if(isset($_GET['username']))
{
    $username = urldecode($_GET['username']);
    require 'form_data_user.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_user.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require 'subclasses/user.php';
        $dbh_user = new user;

        $object_name = 'dbh_user';
        require 'components/create_form_data.php';

        $dbh_user->delete($arr_form_data);

        redirect("listview_user.php?$query_string");
    }
}
require 'subclasses/user_html.php';
$html = new user_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('username');

$html->detail_view = TRUE;

$html->draw_controls('delete');

$html->draw_footer();
