<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Edit user passport groups');

if(isset($_GET['passport_group_id']))
{
    $passport_group_id = urldecode($_GET['passport_group_id']);
    require 'form_data_user_passport_groups.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/user_passport_groups.php';
    $dbh_user_passport_groups = new user_passport_groups;

    $object_name = 'dbh_user_passport_groups';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_user_passport_groups.php?$query_string");
    }

    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_user_passport_groups->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_user_passport_groups->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_user_passport_groups->edit($arr_form_data);
            redirect("listview_user_passport_groups.php?$query_string");
        }
    }
}
require 'subclasses/user_passport_groups_html.php';
$html = new user_passport_groups_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('passport_group_id');


$html->draw_controls('edit');

$html->draw_footer();
