<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('View person');

$page_title       = 'ListView: %%';
$db_subclass      = 'person';
$html_subclass    = 'person_html';
$arr_pkey_name = array('person_id');
$results_per_page = LISTVIEW_RESULTS_PER_PAGE;

//user links / passport tags
$add_link         = 'Add person';
$edit_link        = 'Edit person';
$delete_link      = 'Delete person';
$view_link        = 'View person';

//pages - set to empty if you don't want to include them in the listview
$add_page         = 'add_person.php';
$edit_page        = 'edit_person.php';
$delete_page      = 'delete_person.php';
$view_page        = 'detailview_person.php';
$csv_page         = 'csv_person.php';
$report_page      = 'reporter_person.php';

//Extra entries under operations column (name of include file, not html code)
$operations_extra = '';

//Formatting and alignment options for data columns
$arr_formatting   = array();
$arr_alignment    = array();

require 'components/listview_proc_head.php';
require 'components/listview_proc_html.php';
require 'components/listview_proc_query.php';
require 'components/listview_body_head.php';
require 'components/listview_body_data.php';
require 'components/listview_body_end.php';
