<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit otevaluationitems');

if(isset($_GET['period']) && isset($_GET['item_id']))
{
    $period = urldecode($_GET['period']);
    $item_id = urldecode($_GET['item_id']);
    require 'form_data_otevaluationitems.php';
    $orig_period = $period;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/otevaluationitems.php';
    $dbh_otevaluationitems = new otevaluationitems;

    $object_name = 'dbh_otevaluationitems';
    require 'components/create_form_data.php';
    $arr_form_data['orig_period'] = $_POST['orig_period'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_otevaluationitems.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_otevaluationitems->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_otevaluationitems->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_otevaluationitems->edit($arr_form_data);


            redirect("listview_otevaluationitems.php?$query_string");
        }
    }
}
require 'subclasses/otevaluationitems_html.php';
$html = new otevaluationitems_html;
$html->draw_header('Edit Otevaluationitems', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('item_id');
$html->draw_hidden('orig_period');
$html->draw_controls('edit');

$html->draw_footer();