<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete award');

if(isset($_GET['award_id']))
{
    $award_id = urldecode($_GET['award_id']);
    require_once 'form_data_award.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_award.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/award.php';
        $dbh_award = new award;

        $object_name = 'dbh_award';
        require 'components/create_form_data.php';

        $dbh_award->delete($arr_form_data);


        redirect("listview_award.php?$query_string");
    }
}
require 'subclasses/award_html.php';
$html = new award_html;
$html->draw_header('Delete Award', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('award_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();