<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete office docs');

if(isset($_GET['code_1']) && isset($_GET['code_2']) && isset($_GET['code_3']))
{
    $code_1 = urldecode($_GET['code_1']);
    $code_2 = urldecode($_GET['code_2']);
    $code_3 = urldecode($_GET['code_3']);
    require_once 'form_data_office_docs.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_office_docs.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/office_docs.php';
        $dbh_office_docs = new office_docs;

        $object_name = 'dbh_office_docs';
        require 'components/create_form_data.php';

        $dbh_office_docs->delete($arr_form_data);


        redirect("listview_office_docs.php?$query_string");
    }
}
require 'subclasses/office_docs_html.php';
$html = new office_docs_html;
$html->draw_header('Delete Office Docs', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('code_1');
$html->draw_hidden('code_2');
$html->draw_hidden('code_3');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();