<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete salary grade');

if(isset($_GET['salary_grade_id']))
{
    $salary_grade_id = urldecode($_GET['salary_grade_id']);
    require_once 'form_data_salary_grade.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_salary_grade.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/salary_grade.php';
        $dbh_salary_grade = new salary_grade;

        $object_name = 'dbh_salary_grade';
        require 'components/create_form_data.php';

        $dbh_salary_grade->delete($arr_form_data);


        redirect("listview_salary_grade.php?$query_string");
    }
}
require 'subclasses/salary_grade_html.php';
$html = new salary_grade_html;
$html->draw_header('Delete Salary Grade', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('salary_grade_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();