<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View office docs');

if(isset($_GET['code_1']) && isset($_GET['code_2']) && isset($_GET['code_3']))
{
    $code_1 = urldecode($_GET['code_1']);
    $code_2 = urldecode($_GET['code_2']);
    $code_3 = urldecode($_GET['code_3']);
    require 'form_data_office_docs.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_back']);

    if($_POST['btn_back'])
    {
        log_action('Pressed cancel button');
        require 'components/query_string_standard.php';
        redirect("listview_office_docs.php?$query_string");
    }
}
require 'subclasses/office_docs_html.php';
$html = new office_docs_html;
$html->draw_header('Detail View: Office Docs', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->detail_view = TRUE;
$html->draw_controls('view');

$html->draw_footer();