<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit office docs');

if(isset($_GET['code_1']) && isset($_GET['code_2']) && isset($_GET['code_3']))
{
    $code_1 = urldecode($_GET['code_1']);
    $code_2 = urldecode($_GET['code_2']);
    $code_3 = urldecode($_GET['code_3']);
    require 'form_data_office_docs.php';
    $orig_code_1 = $code_1;
    $orig_code_2 = $code_2;
    $orig_code_3 = $code_3;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/office_docs.php';
    $dbh_office_docs = new office_docs;

    $object_name = 'dbh_office_docs';
    require 'components/create_form_data.php';
    $arr_form_data['orig_code_1'] = $_POST['orig_code_1'];
    $arr_form_data['orig_code_2'] = $_POST['orig_code_2'];
    $arr_form_data['orig_code_3'] = $_POST['orig_code_3'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_office_docs.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_office_docs->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_office_docs->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_office_docs->edit($arr_form_data);


            redirect("listview_office_docs.php?$query_string");
        }
    }
}
require 'subclasses/office_docs_html.php';
$html = new office_docs_html;
$html->draw_header('Edit Office Docs', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_code_1');
$html->draw_hidden('orig_code_2');
$html->draw_hidden('orig_code_3');
$html->draw_controls('edit');

$html->draw_footer();