<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit facultyload');

if(isset($_GET['load_id']))
{
    $load_id = urldecode($_GET['load_id']);
    require 'form_data_facultyload.php';
    $orig_load_id = $load_id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/facultyload.php';
    $dbh_facultyload = new facultyload;

    $object_name = 'dbh_facultyload';
    require 'components/create_form_data.php';
    $arr_form_data['orig_load_id'] = $_POST['orig_load_id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_facultyload.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_facultyload->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_facultyload->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_facultyload->edit($arr_form_data);

            redirect("listview_facultyload.php?$query_string");
        }
    }
}
require 'subclasses/facultyload_html.php';
$html = new facultyload_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_load_id');
$html->draw_controls('edit');

$html->draw_footer();