<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add refsubjectofferinghdr');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/refsubjectofferinghdr.php';
    $dbh_refsubjectofferinghdr = new refsubjectofferinghdr;

    $object_name = 'dbh_refsubjectofferinghdr';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_refsubjectofferinghdr.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_refsubjectofferinghdr->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_refsubjectofferinghdr->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_refsubjectofferinghdr->add($arr_form_data);
            $subject_offering_id = $dbh_refsubjectofferinghdr->auto_id;
            require_once 'subclasses/refsubjectofferingdtl.php';
            $dbh_refsubjectofferinghdr = new refsubjectofferingdtl;
            for($a=0; $a<$refsubjectofferingdtl_count;$a++)
            {
                
                $param = array(
                               'subject_offering_id'=>$subject_offering_id,
                               'time'=>$cf_refsubjectofferingdtl_time[$a],
                               'time_start'=>$cf_refsubjectofferingdtl_time_start[$a],
                               'time_end'=>$cf_refsubjectofferingdtl_time_end[$a],
                               'day'=>$cf_refsubjectofferingdtl_day[$a],
                               'room'=>$cf_refsubjectofferingdtl_room[$a],
                               'room_type'=>$cf_refsubjectofferingdtl_room_type[$a],
                               'occupied'=>$cf_refsubjectofferingdtl_occupied[$a]
                              );
                $dbh_refsubjectofferinghdr->add($param);
            }


            redirect("listview_refsubjectofferinghdr.php?$query_string");
        }
    }
}
require 'subclasses/refsubjectofferinghdr_html.php';
$html = new refsubjectofferinghdr_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();