<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View otevaluationresults');

if(isset($_GET['period']) && isset($_GET['target_id']) && isset($_GET['class_id']))
{
    $period = urldecode($_GET['period']);
    $target_id = urldecode($_GET['target_id']);
    $class_id = urldecode($_GET['class_id']);
    require 'form_data_otevaluationresults.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_back']);

    if($_POST['btn_back'])
    {
        log_action('Pressed cancel button');
        require 'components/query_string_standard.php';
        redirect("listview_otevaluationresults.php?$query_string");
    }
}
require 'subclasses/otevaluationresults_html.php';
$html = new otevaluationresults_html;
$html->draw_header('Detail View: Otevaluationresults', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->detail_view = TRUE;
$html->draw_controls('view');

$html->draw_footer();