<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete term');

if(isset($_GET['term_id']))
{
    $term_id = urldecode($_GET['term_id']);
    require_once 'form_data_term.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_term.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/term.php';
        $dbh_term = new term;

        $object_name = 'dbh_term';
        require 'components/create_form_data.php';


        $dbh_term->delete($arr_form_data);

        redirect("listview_term.php?$query_string");
    }
}
require 'subclasses/term_html.php';
$html = new term_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('term_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();