<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit otevaluationresultsgrouped');

if(isset($_GET['period']) && isset($_GET['target_id']) && isset($_GET['group_id']) && isset($_GET['subject_code']) && isset($_GET['section']))
{
    $period = urldecode($_GET['period']);
    $target_id = urldecode($_GET['target_id']);
    $group_id = urldecode($_GET['group_id']);
    $subject_code = urldecode($_GET['subject_code']);
    $section = urldecode($_GET['section']);
    require 'form_data_otevaluationresultsgrouped.php';
    $orig_period = $period;
    $orig_target_id = $target_id;
    $orig_group_id = $group_id;
    $orig_subject_code = $subject_code;
    $orig_section = $section;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/otevaluationresultsgrouped.php';
    $dbh_otevaluationresultsgrouped = new otevaluationresultsgrouped;

    $object_name = 'dbh_otevaluationresultsgrouped';
    require 'components/create_form_data.php';
    $arr_form_data['orig_period'] = $_POST['orig_period'];
    $arr_form_data['orig_target_id'] = $_POST['orig_target_id'];
    $arr_form_data['orig_group_id'] = $_POST['orig_group_id'];
    $arr_form_data['orig_subject_code'] = $_POST['orig_subject_code'];
    $arr_form_data['orig_section'] = $_POST['orig_section'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_otevaluationresultsgrouped.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_otevaluationresultsgrouped->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_otevaluationresultsgrouped->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_otevaluationresultsgrouped->edit($arr_form_data);


            redirect("listview_otevaluationresultsgrouped.php?$query_string");
        }
    }
}
require 'subclasses/otevaluationresultsgrouped_html.php';
$html = new otevaluationresultsgrouped_html;
$html->draw_header('Edit Otevaluationresultsgrouped', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_period');
$html->draw_hidden('orig_target_id');
$html->draw_hidden('orig_group_id');
$html->draw_hidden('orig_subject_code');
$html->draw_hidden('orig_section');
$html->draw_controls('edit');

$html->draw_footer();