<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit reftermperiod');

if(isset($_GET['term_id']) && isset($_GET['period']))
{
    $term_id = urldecode($_GET['term_id']);
    $period = urldecode($_GET['period']);
    require 'form_data_reftermperiod.php';
    $orig_term_id = $term_id;
    $orig_period = $period;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/reftermperiod.php';
    $dbh_reftermperiod = new reftermperiod;

    $object_name = 'dbh_reftermperiod';
    require 'components/create_form_data.php';
    $arr_form_data['orig_term_id'] = $_POST['orig_term_id'];
    $arr_form_data['orig_period'] = $_POST['orig_period'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_reftermperiod.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_reftermperiod->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_reftermperiod->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_reftermperiod->edit($arr_form_data);

            redirect("listview_reftermperiod.php?$query_string");
        }
    }
}
require 'subclasses/reftermperiod_html.php';
$html = new reftermperiod_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_term_id');
$html->draw_hidden('orig_period');
$html->draw_controls('edit');

$html->draw_footer();