<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('View refsubjectoteclassification');

if(isset($_GET['period']) && isset($_GET['subject_id']))
{
    $period = urldecode($_GET['period']);
    $subject_id = urldecode($_GET['subject_id']);
    require 'form_data_refsubjectoteclassification.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_back']);

    if($_POST['btn_back'])
    {
        log_action('Pressed cancel button');
        require 'components/query_string_standard.php';
        redirect("listview_refsubjectoteclassification.php?$query_string");
    }
}
require 'subclasses/refsubjectoteclassification_html.php';
$html = new refsubjectoteclassification_html;
$html->draw_header('Detail View: Refsubjectoteclassification', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->detail_view = TRUE;
$html->draw_controls('view');

$html->draw_footer();