<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit refsubjectoteclassification');

if(isset($_GET['period']) && isset($_GET['subject_id']))
{
    $period = urldecode($_GET['period']);
    $subject_id = urldecode($_GET['subject_id']);
    require 'form_data_refsubjectoteclassification.php';
    $orig_period = $period;
    $orig_subject_id = $subject_id;
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/refsubjectoteclassification.php';
    $dbh_refsubjectoteclassification = new refsubjectoteclassification;

    $object_name = 'dbh_refsubjectoteclassification';
    require 'components/create_form_data.php';
    $arr_form_data['orig_period'] = $_POST['orig_period'];
    $arr_form_data['orig_subject_id'] = $_POST['orig_subject_id'];
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_refsubjectoteclassification.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_refsubjectoteclassification->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_refsubjectoteclassification->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_refsubjectoteclassification->edit($arr_form_data);


            redirect("listview_refsubjectoteclassification.php?$query_string");
        }
    }
}
require 'subclasses/refsubjectoteclassification_html.php';
$html = new refsubjectoteclassification_html;
$html->draw_header('Edit Refsubjectoteclassification', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('orig_period');
$html->draw_hidden('orig_subject_id');
$html->draw_controls('edit');

$html->draw_footer();