<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Security Monitor');

require 'reporter_class.php';
$reporter = cobalt_load_class('system_log_rpt');
require 'components/reporter_result_query_constructor.php';
require 'components/reporter_result_body.php';